import {   LayoutDashboard, Activity, BarChart3, Bell, Sparkles,
  MapPin, FileText, Settings, Radio,
  Shield, Brain, ArrowLeftRight, Search, Cpu, Server, PlusCircle, Plug, HeartPulse,
  Settings2, TrendingUp, Layers, Zap, Users, AlertTriangle,
  Heart, Target, Scale, MapPinOff, GitBranch, PowerOff, BookOpen, MessageSquare,
  FlaskConical, DollarSign, RadioTower, ArrowRightLeft as ArrowSwap, Gauge, Globe, FileSearch, Crown, GitCompare, Phone,
  CreditCardIcon, Languages, Bot, FolderTree, Building2, Trophy, LineChart, Box,
} from 'lucide-react';
import type { ViewType } from '@/types';

export const NAV_ITEMS: { view: ViewType; labelKey: string; icon: typeof LayoutDashboard; group?: string }[] = [
  { view: 'dashboard', labelKey: 'nav.dashboard', icon: LayoutDashboard, group: 'Operations' },
  { view: 'monitoring', labelKey: 'nav.monitoring', icon: Activity, group: 'Operations' },
  { view: 'son', labelKey: 'nav.son', icon: Cpu, group: 'Operations' },
  { view: 'onboarding', labelKey: 'nav.onboarding', icon: PlusCircle, group: 'Operations' },
  { view: 'live', labelKey: 'nav.live', icon: Activity, group: 'Operations' },
  { view: 'incidents', labelKey: 'nav.incidents', icon: AlertTriangle, group: 'Operations' },
  { view: 'outages', labelKey: 'nav.outages', icon: PowerOff, group: 'Operations' },
  { view: 'spectrum', labelKey: 'nav.spectrum', icon: RadioTower, group: 'Operations' },
  { view: 'kpi', labelKey: 'nav.kpi', icon: BarChart3, group: 'Analytics' },
  { view: 'alerts', labelKey: 'nav.alerts', icon: Bell, group: 'Analytics' },
  { view: 'coverage', labelKey: 'nav.coverage', icon: MapPin, group: 'Analytics' },
  { view: 'correlation', labelKey: 'nav.correlation', icon: ArrowLeftRight, group: 'Analytics' },
  { view: 'qoe', labelKey: 'nav.qoe', icon: HeartPulse, group: 'Analytics' },
  { view: 'capacity', labelKey: 'nav.capacity', icon: TrendingUp, group: 'Analytics' },
  { view: 'handover', labelKey: 'nav.handover', icon: ArrowSwap, group: 'Analytics' },
  { view: 'load', labelKey: 'nav.load', icon: Scale, group: 'Analytics' },
  { view: 'interference', labelKey: 'nav.interference', icon: Radio, group: 'Analytics' },
  { view: 'coverage-holes', labelKey: 'nav.coverageHoles', icon: MapPinOff, group: 'Analytics' },
  { view: 'vendor-compare', labelKey: 'nav.vendorCompare', icon: GitCompare, group: 'Analytics' },
  { view: 'services', labelKey: 'nav.services', icon: Globe, group: 'Analytics' },
  { view: 'geomarketing', labelKey: 'nav.geomarketing', icon: Globe, group: 'Analytics' },
  { view: 'network-commercial', labelKey: 'nav.networkCommercial', icon: ArrowLeftRight, group: 'Intelligence' },
  { view: 'wilaya-intelligence', labelKey: 'nav.wilayaIntelligence', icon: Building2, group: 'Intelligence' },
  { view: 'value-proposition', labelKey: 'nav.valueProposition', icon: Trophy, group: 'Intelligence' },
  { view: 'slicing', labelKey: 'nav.slicing', icon: Layers, group: 'Intelligence' },
  { view: 'energy', labelKey: 'nav.energy', icon: Zap, group: 'Intelligence' },
  { view: 'faults', labelKey: 'nav.faults', icon: Brain, group: 'Intelligence' },
  { view: 'subscribers', labelKey: 'nav.subscribers', icon: Users, group: 'Intelligence' },
  { view: 'health', labelKey: 'nav.health', icon: Heart, group: 'Intelligence' },
  { view: 'benchmark', labelKey: 'nav.benchmark', icon: Target, group: 'Intelligence' },
  { view: 'playbooks', labelKey: 'nav.playbooks', icon: BookOpen, group: 'Intelligence' },
  { view: 'assistant', labelKey: 'nav.assistant', icon: MessageSquare, group: 'Intelligence' },
  { view: 'npi', labelKey: 'nav.npi', icon: Gauge, group: 'Intelligence' },
  { view: 'trends', labelKey: 'nav.trends', icon: TrendingUp, group: 'Intelligence' },
  { view: 'simulations', labelKey: 'nav.simulations', icon: FlaskConical, group: 'Intelligence' },
  { view: 'roi', labelKey: 'nav.roi', icon: DollarSign, group: 'Intelligence' },
  { view: 'evolution', labelKey: 'nav.evolution', icon: ArrowSwap, group: 'Intelligence' },
  { view: 'audit', labelKey: 'nav.audit', icon: FileSearch, group: 'Intelligence' },
  { view: 'executive', labelKey: 'nav.executive', icon: Crown, group: 'Intelligence' },
  { view: 'optimizer', labelKey: 'nav.optimizer', icon: Sparkles, group: 'AI Engine' },
  { view: 'rca', labelKey: 'nav.rca', icon: Search, group: 'AI Engine' },
  { view: 'anomaly', labelKey: 'nav.anomaly', icon: Brain, group: 'AI Engine' },
  { view: 'policies', labelKey: 'nav.policies', icon: Shield, group: 'Automation' },
  { view: 'changes', labelKey: 'nav.changes', icon: GitBranch, group: 'Automation' },
  { view: 'vendors', labelKey: 'nav.vendors', icon: Plug, group: 'Automation' },
  { view: 'oss-integration', labelKey: 'nav.ossIntegration', icon: Server, group: 'Automation' },
  { view: 'crm-integration', labelKey: 'nav.crmIntegration', icon: Phone, group: 'Automation' },
  { view: 'billing-integration', labelKey: 'nav.billingIntegration', icon: CreditCardIcon, group: 'Automation' },
  { view: 'multi-agent', labelKey: 'nav.multiAgent', icon: Bot, group: 'AI Engine' },
  { view: 'data-pipeline', labelKey: 'nav.dataPipeline', icon: FolderTree, group: 'AI Engine' },
  { view: 'predictive', labelKey: 'nav.predictive', icon: LineChart, group: 'AI Engine' },
  { view: 'digital-twin', labelKey: 'nav.digitalTwin', icon: Box, group: 'AI Engine' },
  { view: 'integration-hub', labelKey: 'nav.integrationHub', icon: GitBranch, group: 'AI Engine' },
  { view: 'reports', labelKey: 'nav.reports', icon: FileText, group: 'System' },
  { view: 'sla', labelKey: 'nav.sla', icon: Shield, group: 'System' },
  { view: 'config', labelKey: 'nav.config', icon: Settings2, group: 'System' },
  { view: 'settings', labelKey: 'nav.settings', icon: Settings, group: 'System' },
];

export const VIEW_TITLE_KEYS: Record<ViewType, string> = {
  dashboard: 'title.dashboard', monitoring: 'title.monitoring', son: 'title.son', onboarding: 'title.onboarding',
  kpi: 'title.kpi', alerts: 'title.alerts', optimizer: 'title.optimizer', rca: 'title.rca',
  coverage: 'title.coverage', reports: 'title.reports', settings: 'title.settings', sla: 'title.sla',
  anomaly: 'title.anomaly', correlation: 'title.correlation', policies: 'title.policies', vendors: 'title.vendors',
  qoe: 'title.qoe', capacity: 'title.capacity', slicing: 'title.slicing', energy: 'title.energy',
  faults: 'title.faults', subscribers: 'title.subscribers', incidents: 'title.incidents', config: 'title.config',
  live: 'title.live', health: 'title.health', benchmark: 'title.benchmark', handover: 'title.handover',
  load: 'title.load', interference: 'title.interference', 'coverage-holes': 'title.coverageHoles',
  changes: 'title.changes', outages: 'title.outages', playbooks: 'title.playbooks', assistant: 'title.assistant',
  simulations: 'title.simulations', trends: 'title.trends', roi: 'title.roi', spectrum: 'title.spectrum',
  evolution: 'title.evolution', npi: 'title.npi', services: 'title.services', audit: 'title.audit',
  executive: 'title.executive', 'vendor-compare': 'title.vendorCompare',
  'oss-integration': 'title.ossIntegration', 'crm-integration': 'title.crmIntegration',
  'billing-integration': 'title.billingIntegration', 'multi-agent': 'title.multiAgent',
  'data-pipeline': 'title.dataPipeline', 'integration-hub': 'title.integrationHub',
  geomarketing: 'geo.title', 'network-commercial': 'title.networkCommercial',
  'wilaya-intelligence': 'title.wilayaIntelligence', 'value-proposition': 'title.valueProposition',
  predictive: 'title.predictive', 'digital-twin': 'title.digitalTwin',
};

export const NAV_GROUP_KEYS: Record<string, string> = {
  'Operations': 'nav.group.operations', 'Analytics': 'nav.group.analytics',
  'Intelligence': 'nav.group.intelligence', 'AI Engine': 'nav.group.aiEngine',
  'Automation': 'nav.group.automation', 'System': 'nav.group.system',
};
