
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.NetworkSiteScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  technology: 'technology',
  region: 'region',
  status: 'status',
  latitude: 'latitude',
  longitude: 'longitude',
  altitude: 'altitude',
  frequency: 'frequency',
  bandwidth: 'bandwidth',
  maxCapacity: 'maxCapacity',
  vendor: 'vendor',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KpiMetricScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  timestamp: 'timestamp',
  rssi: 'rssi',
  rsrp: 'rsrp',
  rsrq: 'rsrq',
  sinr: 'sinr',
  rscp: 'rscp',
  ecno: 'ecno',
  rxlev: 'rxlev',
  cqichannel: 'cqichannel',
  downloadThroughput: 'downloadThroughput',
  uploadThroughput: 'uploadThroughput',
  latency: 'latency',
  jitter: 'jitter',
  packetLoss: 'packetLoss',
  availability: 'availability',
  activeUsers: 'activeUsers',
  handoverSuccessRate: 'handoverSuccessRate',
  dropRate: 'dropRate',
  blockedCallRate: 'blockedCallRate',
  prbUtilization: 'prbUtilization',
  createdAt: 'createdAt'
};

exports.Prisma.AlertRuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  technology: 'technology',
  metric: 'metric',
  condition: 'condition',
  threshold: 'threshold',
  severity: 'severity',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AlertScalarFieldEnum = {
  id: 'id',
  ruleId: 'ruleId',
  siteId: 'siteId',
  technology: 'technology',
  metric: 'metric',
  value: 'value',
  threshold: 'threshold',
  condition: 'condition',
  severity: 'severity',
  message: 'message',
  acknowledged: 'acknowledged',
  correlatedGroupId: 'correlatedGroupId',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt'
};

exports.Prisma.OptimizationLogScalarFieldEnum = {
  id: 'id',
  technology: 'technology',
  siteId: 'siteId',
  siteName: 'siteName',
  category: 'category',
  issue: 'issue',
  recommendation: 'recommendation',
  impact: 'impact',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NetworkParameterScalarFieldEnum = {
  id: 'id',
  technology: 'technology',
  parameter: 'parameter',
  displayName: 'displayName',
  currentValue: 'currentValue',
  unit: 'unit',
  minRange: 'minRange',
  maxRange: 'maxRange',
  description: 'description',
  category: 'category',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SLATargetScalarFieldEnum = {
  id: 'id',
  technology: 'technology',
  metric: 'metric',
  targetValue: 'targetValue',
  condition: 'condition',
  severity: 'severity',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AnomalyEventScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  metric: 'metric',
  actualValue: 'actualValue',
  expectedValue: 'expectedValue',
  zScore: 'zScore',
  severity: 'severity',
  status: 'status',
  description: 'description',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  action: 'action',
  oldValue: 'oldValue',
  newValue: 'newValue',
  description: 'description',
  technology: 'technology',
  createdAt: 'createdAt'
};

exports.Prisma.SonModuleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  displayName: 'displayName',
  technology: 'technology',
  description: 'description',
  enabled: 'enabled',
  mode: 'mode',
  schedule: 'schedule',
  parameters: 'parameters',
  stats: 'stats',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SonActionScalarFieldEnum = {
  id: 'id',
  moduleId: 'moduleId',
  siteId: 'siteId',
  technology: 'technology',
  actionType: 'actionType',
  parameter: 'parameter',
  previousValue: 'previousValue',
  newValue: 'newValue',
  reason: 'reason',
  status: 'status',
  kpiBefore: 'kpiBefore',
  kpiAfter: 'kpiAfter',
  impactScore: 'impactScore',
  rollbackReason: 'rollbackReason',
  appliedAt: 'appliedAt',
  rolledBackAt: 'rolledBackAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NeighborRelationScalarFieldEnum = {
  id: 'id',
  servingCellId: 'servingCellId',
  neighborCellId: 'neighborCellId',
  neighborCellName: 'neighborCellName',
  neighborCellCode: 'neighborCellCode',
  technology: 'technology',
  relationType: 'relationType',
  hoType: 'hoType',
  status: 'status',
  hoSuccessRate: 'hoSuccessRate',
  lastUpdated: 'lastUpdated'
};

exports.Prisma.PolicyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  technology: 'technology',
  triggerType: 'triggerType',
  triggerConfig: 'triggerConfig',
  actionModules: 'actionModules',
  scope: 'scope',
  scopeValue: 'scopeValue',
  priority: 'priority',
  enabled: 'enabled',
  cooldownMins: 'cooldownMins',
  stats: 'stats',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PolicyExecutionScalarFieldEnum = {
  id: 'id',
  policyId: 'policyId',
  status: 'status',
  triggerReason: 'triggerReason',
  affectedSites: 'affectedSites',
  actionsTaken: 'actionsTaken',
  kpiImpact: 'kpiImpact',
  rollbackReason: 'rollbackReason',
  durationMs: 'durationMs',
  createdAt: 'createdAt',
  completedAt: 'completedAt'
};

exports.Prisma.QoEMetricScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  timestamp: 'timestamp',
  mosScore: 'mosScore',
  dataRateExperienced: 'dataRateExperienced',
  callSetupTime: 'callSetupTime',
  callDropRate: 'callDropRate',
  webPageLoadTime: 'webPageLoadTime',
  videoStartTime: 'videoStartTime',
  pingLatency: 'pingLatency',
  jitterExperience: 'jitterExperience',
  satisfactionIndex: 'satisfactionIndex',
  subscriberCount: 'subscriberCount',
  complaintCount: 'complaintCount',
  createdAt: 'createdAt'
};

exports.Prisma.VendorProfileScalarFieldEnum = {
  id: 'id',
  vendor: 'vendor',
  displayName: 'displayName',
  technologies: 'technologies',
  apiType: 'apiType',
  apiEndpoint: 'apiEndpoint',
  credentials: 'credentials',
  status: 'status',
  lastSync: 'lastSync',
  stats: 'stats',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SiteOnboardingScalarFieldEnum = {
  id: 'id',
  siteName: 'siteName',
  siteCode: 'siteCode',
  technology: 'technology',
  region: 'region',
  vendor: 'vendor',
  latitude: 'latitude',
  longitude: 'longitude',
  altitude: 'altitude',
  frequency: 'frequency',
  bandwidth: 'bandwidth',
  maxCapacity: 'maxCapacity',
  status: 'status',
  assignedPci: 'assignedPci',
  assignedFreq: 'assignedFreq',
  initialNeighbors: 'initialNeighbors',
  kpiBaseline: 'kpiBaseline',
  errorMessage: 'errorMessage',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CapacityForecastScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  region: 'region',
  metric: 'metric',
  currentValue: 'currentValue',
  forecastValue: 'forecastValue',
  forecastHorizon: 'forecastHorizon',
  growthRate: 'growthRate',
  capacityLimit: 'capacityLimit',
  utilizationAtLimit: 'utilizationAtLimit',
  confidence: 'confidence',
  riskLevel: 'riskLevel',
  recommendation: 'recommendation',
  timestamp: 'timestamp',
  createdAt: 'createdAt'
};

exports.Prisma.NetworkSliceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sliceType: 'sliceType',
  technology: 'technology',
  status: 'status',
  siteId: 'siteId',
  sst: 'sst',
  sd: 'sd',
  maxBandwidth: 'maxBandwidth',
  guaranteedBw: 'guaranteedBw',
  maxUsers: 'maxUsers',
  priorityLevel: 'priorityLevel',
  latencyTarget: 'latencyTarget',
  reliabilityTarget: 'reliabilityTarget',
  currentLoad: 'currentLoad',
  activeUsers: 'activeUsers',
  avgThroughput: 'avgThroughput',
  avgLatency: 'avgLatency',
  qci: 'qci',
  FiveQi: 'FiveQi',
  parameters: 'parameters',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EnergyMetricScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  timestamp: 'timestamp',
  powerConsumption: 'powerConsumption',
  energyConsumed: 'energyConsumed',
  activeUsers: 'activeUsers',
  trafficLoad: 'trafficLoad',
  temperature: 'temperature',
  sleepMode: 'sleepMode',
  mode: 'mode',
  co2Emission: 'co2Emission',
  solarGeneration: 'solarGeneration',
  batteryLevel: 'batteryLevel',
  createdAt: 'createdAt'
};

exports.Prisma.FaultPredictionScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  component: 'component',
  faultType: 'faultType',
  probability: 'probability',
  severity: 'severity',
  status: 'status',
  confidence: 'confidence',
  indicators: 'indicators',
  recommendedAction: 'recommendedAction',
  estimatedTimeToFail: 'estimatedTimeToFail',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubscriberSegmentScalarFieldEnum = {
  id: 'id',
  segmentName: 'segmentName',
  technology: 'technology',
  criteria: 'criteria',
  subscriberCount: 'subscriberCount',
  avgDataUsage: 'avgDataUsage',
  avgVoiceMinutes: 'avgVoiceMinutes',
  arpu: 'arpu',
  churnRisk: 'churnRisk',
  satisfactionScore: 'satisfactionScore',
  topServices: 'topServices',
  peakHour: 'peakHour',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.IncidentScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  technology: 'technology',
  siteId: 'siteId',
  severity: 'severity',
  status: 'status',
  category: 'category',
  priority: 'priority',
  assignedTo: 'assignedTo',
  reportedBy: 'reportedBy',
  mttrTarget: 'mttrTarget',
  mtbfValue: 'mtbfValue',
  rootCause: 'rootCause',
  resolution: 'resolution',
  affectedSites: 'affectedSites',
  relatedAlerts: 'relatedAlerts',
  tags: 'tags',
  slaBreach: 'slaBreach',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConfigTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  technology: 'technology',
  category: 'category',
  description: 'description',
  vendor: 'vendor',
  parameters: 'parameters',
  isDefault: 'isDefault',
  applyCount: 'applyCount',
  lastApplied: 'lastApplied',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HealthScoreScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  region: 'region',
  overallScore: 'overallScore',
  coverageScore: 'coverageScore',
  capacityScore: 'capacityScore',
  qualityScore: 'qualityScore',
  reliabilityScore: 'reliabilityScore',
  experienceScore: 'experienceScore',
  grade: 'grade',
  trend: 'trend',
  issues: 'issues',
  timestamp: 'timestamp',
  createdAt: 'createdAt'
};

exports.Prisma.BenchmarkRecordScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  region: 'region',
  metric: 'metric',
  actualValue: 'actualValue',
  benchmarkValue: 'benchmarkValue',
  targetValue: 'targetValue',
  percentileRank: 'percentileRank',
  gap: 'gap',
  status: 'status',
  timestamp: 'timestamp',
  createdAt: 'createdAt'
};

exports.Prisma.HandoverKpiScalarFieldEnum = {
  id: 'id',
  servingCellId: 'servingCellId',
  neighborCellName: 'neighborCellName',
  neighborCellCode: 'neighborCellCode',
  technology: 'technology',
  relationType: 'relationType',
  hoAttempts: 'hoAttempts',
  hoSuccess: 'hoSuccess',
  hoFailures: 'hoFailures',
  hoSuccessRate: 'hoSuccessRate',
  avgPrepTime: 'avgPrepTime',
  avgExecTime: 'avgExecTime',
  pingPongCount: 'pingPongCount',
  tooEarlyCount: 'tooEarlyCount',
  tooLateCount: 'tooLateCount',
  status: 'status',
  recommendation: 'recommendation',
  timestamp: 'timestamp',
  createdAt: 'createdAt'
};

exports.Prisma.CellLoadScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  region: 'region',
  prbUtilDownlink: 'prbUtilDownlink',
  prbUtilUplink: 'prbUtilUplink',
  activeUsers: 'activeUsers',
  maxUsers: 'maxUsers',
  userLoadPct: 'userLoadPct',
  throughputDown: 'throughputDown',
  throughputUp: 'throughputUp',
  balancedScore: 'balancedScore',
  congestionLevel: 'congestionLevel',
  recommendation: 'recommendation',
  timestamp: 'timestamp',
  createdAt: 'createdAt'
};

exports.Prisma.InterferenceEventScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  interferenceType: 'interferenceType',
  severity: 'severity',
  status: 'status',
  sourceCell: 'sourceCell',
  sourceCellName: 'sourceCellName',
  conflictingCell: 'conflictingCell',
  conflictingCellName: 'conflictingCellName',
  frequency: 'frequency',
  pci: 'pci',
  affectedKpis: 'affectedKpis',
  impactScore: 'impactScore',
  recommendation: 'recommendation',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CoverageHoleScalarFieldEnum = {
  id: 'id',
  technology: 'technology',
  region: 'region',
  latitude: 'latitude',
  longitude: 'longitude',
  radiusMeters: 'radiusMeters',
  areaKm2: 'areaKm2',
  signalStrength: 'signalStrength',
  expectedSignal: 'expectedSignal',
  gapDb: 'gapDb',
  severity: 'severity',
  nearestSite: 'nearestSite',
  nearestSiteName: 'nearestSiteName',
  nearestSiteDistKm: 'nearestSiteDistKm',
  affectedUsers: 'affectedUsers',
  recommendation: 'recommendation',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChangeRequestScalarFieldEnum = {
  id: 'id',
  title: 'title',
  technology: 'technology',
  siteId: 'siteId',
  siteName: 'siteName',
  category: 'category',
  parameter: 'parameter',
  previousValue: 'previousValue',
  proposedValue: 'proposedValue',
  reason: 'reason',
  impact: 'impact',
  riskLevel: 'riskLevel',
  status: 'status',
  requestedBy: 'requestedBy',
  approvedBy: 'approvedBy',
  implementedAt: 'implementedAt',
  rollbackReason: 'rollbackReason',
  kpiImpact: 'kpiImpact',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OutageEventScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  region: 'region',
  outageType: 'outageType',
  severity: 'severity',
  status: 'status',
  startedAt: 'startedAt',
  detectedAt: 'detectedAt',
  estimatedDuration: 'estimatedDuration',
  actualDuration: 'actualDuration',
  affectedUsers: 'affectedUsers',
  rootCause: 'rootCause',
  compensationApplied: 'compensationApplied',
  compensationSites: 'compensationSites',
  resolvedAt: 'resolvedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlaybookScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  technology: 'technology',
  description: 'description',
  severity: 'severity',
  estimatedTime: 'estimatedTime',
  usageCount: 'usageCount',
  successRate: 'successRate',
  tags: 'tags',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PlaybookStepScalarFieldEnum = {
  id: 'id',
  playbookId: 'playbookId',
  stepNumber: 'stepNumber',
  title: 'title',
  description: 'description',
  action: 'action',
  target: 'target',
  expectedOutcome: 'expectedOutcome',
  isBlocking: 'isBlocking',
  createdAt: 'createdAt'
};

exports.Prisma.SimulationScenarioScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  technology: 'technology',
  region: 'region',
  siteId: 'siteId',
  category: 'category',
  parameters: 'parameters',
  baselineKpis: 'baselineKpis',
  simulatedKpis: 'simulatedKpis',
  impactScore: 'impactScore',
  recommendation: 'recommendation',
  confidence: 'confidence',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrendForecastScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  region: 'region',
  metric: 'metric',
  forecastPoints: 'forecastPoints',
  horizon: 'horizon',
  trendDirection: 'trendDirection',
  confidence: 'confidence',
  recommendation: 'recommendation',
  timestamp: 'timestamp',
  createdAt: 'createdAt'
};

exports.Prisma.RoiRecordScalarFieldEnum = {
  id: 'id',
  title: 'title',
  category: 'category',
  technology: 'technology',
  siteId: 'siteId',
  siteName: 'siteName',
  investmentCost: 'investmentCost',
  annualSaving: 'annualSaving',
  paybackMonths: 'paybackMonths',
  roiPercentage: 'roiPercentage',
  status: 'status',
  kpiImpact: 'kpiImpact',
  period: 'period',
  periodValue: 'periodValue',
  cumulativeSaving: 'cumulativeSaving',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SpectrumBlockScalarFieldEnum = {
  id: 'id',
  band: 'band',
  bandwidth: 'bandwidth',
  technology: 'technology',
  region: 'region',
  channelCount: 'channelCount',
  utilizedChannels: 'utilizedChannels',
  utilizationPct: 'utilizationPct',
  avgInterference: 'avgInterference',
  avgRsrp: 'avgRsrp',
  refarmCandidate: 'refarmCandidate',
  refarmTargetTech: 'refarmTargetTech',
  refarmPotentialSaving: 'refarmPotentialSaving',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EvolutionPlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sourceTech: 'sourceTech',
  targetTech: 'targetTech',
  region: 'region',
  siteCount: 'siteCount',
  sitesCompleted: 'sitesCompleted',
  estimatedCost: 'estimatedCost',
  spentBudget: 'spentBudget',
  startDate: 'startDate',
  targetDate: 'targetDate',
  status: 'status',
  spectrumGain: 'spectrumGain',
  capacityGain: 'capacityGain',
  riskLevel: 'riskLevel',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NpiRecordScalarFieldEnum = {
  id: 'id',
  siteId: 'siteId',
  technology: 'technology',
  region: 'region',
  overallNpi: 'overallNpi',
  coverageNpi: 'coverageNpi',
  capacityNpi: 'capacityNpi',
  qualityNpi: 'qualityNpi',
  reliabilityNpi: 'reliabilityNpi',
  costEfficiencyNpi: 'costEfficiencyNpi',
  rank: 'rank',
  totalSites: 'totalSites',
  timestamp: 'timestamp',
  createdAt: 'createdAt'
};

exports.Prisma.ServiceOrchestrationScalarFieldEnum = {
  id: 'id',
  serviceName: 'serviceName',
  serviceType: 'serviceType',
  technology: 'technology',
  region: 'region',
  mosScore: 'mosScore',
  latencyMs: 'latencyMs',
  jitterMs: 'jitterMs',
  packetLoss: 'packetLoss',
  throughputMbps: 'throughputMbps',
  availabilityPct: 'availabilityPct',
  userSatisfaction: 'userSatisfaction',
  activeSessions: 'activeSessions',
  kpiViolations: 'kpiViolations',
  slaCompliant: 'slaCompliant',
  issues: 'issues',
  timestamp: 'timestamp',
  createdAt: 'createdAt'
};

exports.Prisma.AuditTrailScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  entityName: 'entityName',
  action: 'action',
  field: 'field',
  previousValue: 'previousValue',
  newValue: 'newValue',
  technology: 'technology',
  category: 'category',
  requestedBy: 'requestedBy',
  approvedBy: 'approvedBy',
  impact: 'impact',
  createdAt: 'createdAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  passwordHash: 'passwordHash',
  avatar: 'avatar',
  phone: 'phone',
  department: 'department',
  isActive: 'isActive',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  displayName: 'displayName',
  description: 'description',
  isSystem: 'isSystem',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  module: 'module',
  action: 'action',
  createdAt: 'createdAt'
};

exports.Prisma.UserRoleScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  permissionId: 'permissionId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  NetworkSite: 'NetworkSite',
  KpiMetric: 'KpiMetric',
  AlertRule: 'AlertRule',
  Alert: 'Alert',
  OptimizationLog: 'OptimizationLog',
  NetworkParameter: 'NetworkParameter',
  SLATarget: 'SLATarget',
  AnomalyEvent: 'AnomalyEvent',
  AuditLog: 'AuditLog',
  SonModule: 'SonModule',
  SonAction: 'SonAction',
  NeighborRelation: 'NeighborRelation',
  Policy: 'Policy',
  PolicyExecution: 'PolicyExecution',
  QoEMetric: 'QoEMetric',
  VendorProfile: 'VendorProfile',
  SiteOnboarding: 'SiteOnboarding',
  CapacityForecast: 'CapacityForecast',
  NetworkSlice: 'NetworkSlice',
  EnergyMetric: 'EnergyMetric',
  FaultPrediction: 'FaultPrediction',
  SubscriberSegment: 'SubscriberSegment',
  Incident: 'Incident',
  ConfigTemplate: 'ConfigTemplate',
  HealthScore: 'HealthScore',
  BenchmarkRecord: 'BenchmarkRecord',
  HandoverKpi: 'HandoverKpi',
  CellLoad: 'CellLoad',
  InterferenceEvent: 'InterferenceEvent',
  CoverageHole: 'CoverageHole',
  ChangeRequest: 'ChangeRequest',
  OutageEvent: 'OutageEvent',
  Playbook: 'Playbook',
  PlaybookStep: 'PlaybookStep',
  SimulationScenario: 'SimulationScenario',
  TrendForecast: 'TrendForecast',
  RoiRecord: 'RoiRecord',
  SpectrumBlock: 'SpectrumBlock',
  EvolutionPlan: 'EvolutionPlan',
  NpiRecord: 'NpiRecord',
  ServiceOrchestration: 'ServiceOrchestration',
  AuditTrail: 'AuditTrail',
  User: 'User',
  Role: 'Role',
  Permission: 'Permission',
  UserRole: 'UserRole',
  RolePermission: 'RolePermission'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
